DROP TABLE IF EXISTS ex12_keyword;

CREATE TABLE ex12_keyword(
book_id INT AUTO_INCREMENT PRIMARY KEY,
keyword VARCHAR(20) NOT NULL
ENGINE=InnoDB;

DROP PROCEDURE keywords;
DELIMITER $$
CREATE PROCEDURE keywords()
BEGIN
DECLARE bkid INT(11);
DECLARE kw1 VARCHAR(20);
DECLARE kw2 VARCHAR(20);
DECLARE kw3 VARCHAR(20);
DECLARE kw4 VARCHAR(20);
DECLARE done INT DEFAULT 0;
DECLARE cur1 CURSOR FOR
	SELECT book_id,kw1,kw2,kw3,kw4
	FROM ex12_book;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET done=1;
OPEN cur1;
FETCH cur1 INTO bkid,kw1,kw2,kw3,kw4;
END WHILE;
END$$
DELIMITER ;
